# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78267402a6a7ad911821e2d24696499c02dfb478aa259d49d609026ad94e06e461250f30b6f2dc8596a237b976049c4ec2e2acbc6a7d88a0e7bbb3a88081704b

test:
  secret_key_base: 0b24731f82816579a60a3bd20990a31427d09950aba881288d26033dbb48bd03ccd3c956c9e33c0180e824b5c9b8c91abf1b39afe4751ca9fd6060564742a824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
